name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '>=3.7'
    - name: deps
      run: |
        pip install -e .
        pip install -r dev-requirements.txt
    - name: lint
      run: pylint groundling 
    - name: test
      run: pytest
